INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('02', '001', 'COLONIAS/PERFUMES', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('25', '001', 'BISCOITOS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('25', '002', 'PAES', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('35', '001', 'ANTISSEPTICO BUCAL', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('35', '002', 'FRALDAS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('02', '002', 'DESODORANTE', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('35', '003', 'PROD CAPILARES', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('35', '004', 'SABONETES', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('35', '006', 'HID E CR CORPORAIS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('35', '007', 'CR DENTAIS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('35', '008', 'ALGODOES', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('35', '010', 'ABSORV E T HIG', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('04', '003', 'BOLINHOS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('35', '009', 'AP E CR DE BARB', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('55', '001', 'AROMAT DE AMBIENTES', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('55', '002', 'ACESSORIOS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('55', '006', 'LIMPA ALUMINO', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('55', '007', 'CERAS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('55', '008', 'DESINFETANTES', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('35', '012', 'ACESSORIOS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('50', '001', 'REPELENTES', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('55', '003', 'MULTIUSOS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('50', '006', 'GEL PARA DORES', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('55', '004', 'SABOES E LAV. ROUPAS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('55', '010', 'LUBRIFICANTES', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '001', 'BISCOITOS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('55', '005', 'RODOS E VASSOURAS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('35', '013', 'PAPEIS HIG', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '002', 'PO PARA SORV', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('55', '011', 'AGUA SANI E ALVEJ', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('50', '003', 'ALCOOL', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('55', '012', 'DESUMID DE AMBIENTES', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('55', '013', 'QUEROSENES', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('55', '014', 'ACIDO MURIA/SODA CAUS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('04', '001', 'PASTILHAS E BOMBONS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '003', 'CAFE', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('35', '014', 'ESC DENTAIS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('04', '002', 'BARRAS E TABLETES', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '023', 'AMENDOINS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '027', 'COCO RALADO', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('06', '001', 'LAMPADAS FLUORESCENTES', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '004', 'ADOCANTES', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('50', '004', 'XAROPES', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '005', 'AROMAT P/ MASSAS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '006', 'FERMENTO EM PO', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '007', 'MEL INDUSTRI', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '008', 'LEITE CONDENSADO', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '009', 'CREME DE LEITE', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '010', 'LEITES E DERIV', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '011', 'ACHOC EM PO', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '025', 'FAR DE AVEIA', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '013', 'PREPARA P/ SOPAS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('15', '004', 'PEIXES', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '015', 'TORRADAS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '016', 'GRANULADOS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '017', 'CASTANHAS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '018', 'AMIDO DE MILHO', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '019', 'GRANOLAS E CEREAIS EM GRAOS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '026', 'TORRESMOS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '028', 'FAVAS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '021', 'FARINHA DE LINHACA', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '022', 'REFRESCO EM PO', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('50', '007', 'CREMES PARA ASSADURAS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '024', 'MIST E COBERT P/ BOLOS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('11', '011', 'BARALHOS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '032', 'SUCOS DE GARRAFA', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '029', 'EM CONSERVA', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '033', 'GELEIAS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('11', '012', 'TESOURAS - EXCETO DE UNHAS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '035', 'GELATINAS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('04', '004', 'EM DEPOSITOS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('15', '005', 'LINGUICA', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('50', '005', 'LUVAS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('08', '001', 'DESCARTAVEIS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('04', '006', 'EM POTE', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('09', '008', 'COPOS E CANECOS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('13', '004', 'BORRACHAS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('13', '005', 'CANETAS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '038', 'MACARROES', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '039', 'CUSCUZ', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('09', '001', 'EM GERAL', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('15', '006', 'QUEIJO', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('35', '036', 'CERAS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '042', 'CAFE SOLUVEL', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '043', 'FUBA DE MILHO', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '044', 'FARIN DE MILHO', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('09', '009', 'GARRAFAS PLASTICAS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '045', 'CAFE COM LEITE', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '046', 'FILTRO DE PAPEL', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('15', '007', 'FRANGO', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('13', '006', 'CORRETIVOS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '049', 'CEREAL INFANTIL', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '050', 'MOLHOS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('50', '008', 'FILTRO SOLAR', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('07', '001', 'SANDALIAS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('09', '010', 'GARRAFAS DE VIDRO', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('09', '003', 'PAPEL ALUMINIO', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('09', '004', 'FILME DE PVC', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('09', '006', 'GUARD, LENC E TOALHAS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('55', '017', 'SACOS PARA LIXO', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('11', '001', 'EM GERAL', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('35', '016', 'URINOL', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('09', '007', 'JARRAS TERMICAS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('09', '011', 'TALHERES', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '077', 'ALHO', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('09', '012', 'SALEIROS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('09', '013', 'ABRIDORES', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('09', '014', 'PENEIRAS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('09', '015', 'FORMAS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('09', '016', 'XIRCARAS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('09', '017', 'PRATOS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('09', '018', 'RALADORES, TRITURADORES E SIMI', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('09', '019', 'PINCEL CULINARIO', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('09', '020', 'PROTETORES DE PIA', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('12', '001', 'MAMADEIRAS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('12', '002', 'CHUPETAS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '020', 'FAR DE ROSCA', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('18', '001', 'ERVAS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('12', '003', 'BICOS PARA MAMADEIRAS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('12', '004', 'PRENDEDOR DE CHUPETAS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('13', '001', 'MARCADORES', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('13', '002', 'LAPISERAS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('09', '021', 'DEPOSITOS/ORGANIZADORES', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('11', '002', 'MASSA EPOXI', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('11', '003', 'FOSFOROS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('13', '003', 'CADERNOS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('09', '022', 'ASSADEIRAS DE VIDRO', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('11', '004', 'VELAS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('30', '001', 'EM GERAL', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('30', '002', 'CACHAÇA/AGUARDENTE', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('30', '003', 'CATUABA', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('30', '004', 'WHISKY', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('30', '005', 'VODKA', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('30', '006', 'CONHAQUE', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '052', 'ARROZ', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '053', 'ACUCAR', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '055', 'SAL', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '058', 'TEMPEROS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '065', 'OLEOS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '066', 'FAR DE TRIGO', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '068', 'ERVAS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '069', 'SALGADOS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '071', 'MASSAS PARA TAPIOCA', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '070', 'BATATA PALHA', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('15', '001', 'MORTADELAS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('06', '002', 'LANTERNAS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('11', '005', 'COLAS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('11', '006', 'PILHAS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('11', '007', 'EXTENSAO', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('35', '022', 'ESMALTES', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('35', '023', 'BATOM', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('14', '001', 'CIGARROS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('14', '002', 'FUMOS PARA CIGARROS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('16', '001', 'IOGURTE', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('16', '002', 'ACHOCOLATADOS LIQUEDOS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('16', '003', 'BEBIDAS LACTEAS DE FRUTAS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('16', '004', 'ENERGETICOS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('16', '005', 'REFRIGERANTES', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('16', '006', 'COALHADA', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('16', '007', 'CERVEJA', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('09', '023', 'COADORES DE CAFÉ', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('16', '008', 'REQUEIJÃO', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('16', '009', 'AGUA DE COCO', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('16', '010', 'AGUA MINERAL', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '076', 'PIMENTAS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('11', '008', 'AVENTAIS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('25', '003', 'BOLOS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '073', 'FARINHAS DE MAND', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('09', '024', 'BORRACHAS P PAN DE PRESSAO', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '074', 'MILHO', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '075', 'FEIJOES', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('55', '018', 'PASTA DE LIMPEZA', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('18', '002', 'PIMENTAS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('35', '026', 'DESOD ANTITRANS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('55', '019', 'DETERGENTES', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('15', '003', 'CARNE', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('55', '020', 'LUSTRA-MOVEIS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('55', '021', 'AMACIANTE DE ROUPAS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('55', '022', 'ESPONJAS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('55', '023', 'PREND DE ROUPAS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('55', '024', 'PANOS DE CHAO/MULTI', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('35', '027', 'FIO DENTAL', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('16', '011', 'MARGARINA/MANTEIGA', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '078', 'OVOS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('35', '028', 'HASTLES FLEX', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('55', '025', 'PEDRAS E PAST SANI', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('15', '002', 'STEAK', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('06', '003', 'LED', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('06', '004', 'HALOGENA', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('06', '005', 'LUMINARIAS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('16', '012', 'LEITE FERMENTADO LIQ', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('14', '003', 'PAPEL P/ CIGARRO', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('35', '029', 'AGUA OXI', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('18', '003', 'OUTROS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('11', '009', 'ISQUEIROS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('11', '010', 'LAMINAS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('55', '026', 'ODORIZANTE DE AMB', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('55', '027', 'VARAL', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('55', '028', 'ALCOOL', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('09', '025', 'FORRO P/ FOGAO', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('55', '029', 'DESODORIZANTE', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('55', '032', 'TIRA MANCHAS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('55', '033', 'LIMPA CERAMICA', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('03', '001', 'RACOES', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('35', '033', 'AMONIACOS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('35', '034', 'TALCOS INFANTIS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('07', '002', 'TENIS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '079', 'GOMA', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('16', '013', 'POLPA', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '072', 'QUIJO RALADO', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('16', '014', 'NATA', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('09', '002', 'SALADEIRAS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('09', '026', 'POTES', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('09', '027', 'LEITEIRA', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('55', '034', 'ESCOVAS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('55', '035', 'INSETICIDAS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('55', '036', 'P/AUTOMOVEIS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('35', '035', 'ACETONA', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('01', '080', 'SOPAS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('16', '015', 'SORVETES', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('35', '037', 'LENCOS/TOALHAS UMIDEC', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('08', '002', 'BALOES DE ANIVERSARIO', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('08', '003', 'EMBALAGENS DE PAPEL', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('08', '004', 'VELAS PARA ANIVERSARIO', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('16', '016', 'MASSAS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('13', '007', 'COLA', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('13', '008', 'TESOURAS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('13', '009', 'APONTADORES', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('35', '038', 'MAQUIAGEM', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('50', '009', 'CURATIVOS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('13', '010', 'REGUAS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('12', '005', 'BRINQUEDOS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('15', '008', 'HAMBURGUERS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('13', '011', 'MOCHILAS E LANCHEIRAS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('13', '012', 'ESTOJOS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('11', '017', 'APARELHOS ELETRONICOS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('13', '013', 'ACESSORIOS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('15', '009', 'PRESUNTO', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('12', '006', 'TOALHAS INFANTIS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('12', '007', 'FRALDAS DE TECIDO INFANTIL', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('35', '039', 'COLONIAS E PERFUMES', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('15', '010', 'SALSICHAS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('17', '001', 'EM GERAL', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('09', '028', 'PANELAS', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('18', '004', 'BATATA INGLESA', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('15', '011', 'PERU', 'N');
INSERT INTO GRUPO (SECCOD, GRPCOD, GRPDES, GRPSINCLD)
           VALUES ('00', '000', 'GRUPO PADRAO', 'N');


COMMIT WORK;

