INSERT INTO SECAO (SECCOD, SECDES, SECTIP, SECSINCLD)
           VALUES ('02', 'PERFUMARIA                    ', NULL, 'N');
INSERT INTO SECAO (SECCOD, SECDES, SECTIP, SECSINCLD)
           VALUES ('01', 'CEREAIS', NULL, 'N');
INSERT INTO SECAO (SECCOD, SECDES, SECTIP, SECSINCLD)
           VALUES ('05', 'OBSOLETO', NULL, 'N');
INSERT INTO SECAO (SECCOD, SECDES, SECTIP, SECSINCLD)
           VALUES ('35', 'HIGIENE E BELEZA              ', NULL, 'N');
INSERT INTO SECAO (SECCOD, SECDES, SECTIP, SECSINCLD)
           VALUES ('10', 'CONGELADOS E EMBUTIDOS', NULL, 'N');
INSERT INTO SECAO (SECCOD, SECDES, SECTIP, SECSINCLD)
           VALUES ('15', 'FRIGORIFICO                   ', NULL, 'N');
INSERT INTO SECAO (SECCOD, SECDES, SECTIP, SECSINCLD)
           VALUES ('20', 'OBSOLETO', NULL, 'N');
INSERT INTO SECAO (SECCOD, SECDES, SECTIP, SECSINCLD)
           VALUES ('25', 'PAES E MASSAS', NULL, 'N');
INSERT INTO SECAO (SECCOD, SECDES, SECTIP, SECSINCLD)
           VALUES ('30', 'BEBIDAS', NULL, 'N');
INSERT INTO SECAO (SECCOD, SECDES, SECTIP, SECSINCLD)
           VALUES ('45', 'OBSOLETO', NULL, 'N');
INSERT INTO SECAO (SECCOD, SECDES, SECTIP, SECSINCLD)
           VALUES ('50', 'FARMACIA                      ', NULL, 'N');
INSERT INTO SECAO (SECCOD, SECDES, SECTIP, SECSINCLD)
           VALUES ('55', 'LIMPEZA                       ', NULL, 'N');
INSERT INTO SECAO (SECCOD, SECDES, SECTIP, SECSINCLD)
           VALUES ('60', 'OBSOLETO', NULL, 'N');
INSERT INTO SECAO (SECCOD, SECDES, SECTIP, SECSINCLD)
           VALUES ('40', 'OBSOLETO', NULL, 'N');
INSERT INTO SECAO (SECCOD, SECDES, SECTIP, SECSINCLD)
           VALUES ('04', 'DOCES', NULL, 'N');
INSERT INTO SECAO (SECCOD, SECDES, SECTIP, SECSINCLD)
           VALUES ('07', 'CALCADOS', NULL, 'N');
INSERT INTO SECAO (SECCOD, SECDES, SECTIP, SECSINCLD)
           VALUES ('08', 'ARTEFATOS PARA FESTAS', NULL, 'N');
INSERT INTO SECAO (SECCOD, SECDES, SECTIP, SECSINCLD)
           VALUES ('09', 'ARTEFATOS PARA COZINHA', NULL, 'N');
INSERT INTO SECAO (SECCOD, SECDES, SECTIP, SECSINCLD)
           VALUES ('06', 'LAMPADAS E LUMINARIAS', NULL, 'N');
INSERT INTO SECAO (SECCOD, SECDES, SECTIP, SECSINCLD)
           VALUES ('11', 'UTILITARIOS', NULL, 'N');
INSERT INTO SECAO (SECCOD, SECDES, SECTIP, SECSINCLD)
           VALUES ('12', 'ARTIGOS INFANTIS', NULL, 'A');
INSERT INTO SECAO (SECCOD, SECDES, SECTIP, SECSINCLD)
           VALUES ('13', 'ARTIGOS ESCOLARES', NULL, 'N');
INSERT INTO SECAO (SECCOD, SECDES, SECTIP, SECSINCLD)
           VALUES ('03', 'ARTIGOS P/ ANIMAIS', NULL, 'N');
INSERT INTO SECAO (SECCOD, SECDES, SECTIP, SECSINCLD)
           VALUES ('14', 'FUMOS E CIGARROS', NULL, 'N');
INSERT INTO SECAO (SECCOD, SECDES, SECTIP, SECSINCLD)
           VALUES ('16', 'FRIOS E LATICINIOS', NULL, 'N');
INSERT INTO SECAO (SECCOD, SECDES, SECTIP, SECSINCLD)
           VALUES ('18', 'HOTIFRUTIGRANJEIRO', NULL, 'N');
INSERT INTO SECAO (SECCOD, SECDES, SECTIP, SECSINCLD)
           VALUES ('17', 'ELETRONICOS', NULL, 'N');
INSERT INTO SECAO (SECCOD, SECDES, SECTIP, SECSINCLD)
           VALUES ('00', 'SECAO PADRAO', NULL, 'N');


COMMIT WORK;

