INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('02', '002', '001', 'TALCO/PO', '', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '012', '001', 'PENTES E ESCOV P/CAB', '96162000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '012', '002', 'TESOURAS', '82142000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '012', '003', 'ALICATES', '82142000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '003', '001', 'CR DE PENT', '33059000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '026', '001', 'AEROSOL', '33072010', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '038', '001', 'COMUNS', '19021900', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '026', '002', 'ROLL ON', '33072090', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('07', '001', '001', 'EM GERAL', '64022000', 'N', 'S', 5, 'A');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '001', '001', 'EM GERAL', '19053100', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '049', '001', 'EM GERAL', '19011090', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '010', '001', 'FRALDAS', '96190000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('55', '008', '001', 'LAVA PISOS 1L', '38089429', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('55', '008', '002', 'LIMPADORES', '38089429', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '013', '001', 'EM GERAL', '48181000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '002', '001', 'FRALDAS', '96190000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('55', '021', '001', '500ML', '34012090', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '045', '001', 'CAFE C/ LEITE', '21011200', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '043', '001', 'EM GERAL', '11022000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '007', '001', 'EM GERAL', '33061000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '004', '001', 'BARRA', '34011190', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '009', '001', 'AP DE BARB', '82121020', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('55', '004', '001', 'BARRA', '34012090', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('16', '003', '001', 'BEBIDAS LACTEAS DE FRUTAS', '20098990', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('25', '001', '001', 'DOCE', '19053100', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('55', '022', '002', 'COMUNS', '68053090', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '024', '001', 'MIST P/ BOLOS', '19012000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '010', '001', 'INTEGRAL', '04022110', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '003', '002', 'SHAMPOO', '33051000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '004', '002', 'LIQUEDOS', '34013000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '003', '003', 'COND', '33059000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '003', '004', 'AMPOLA CAP', '33059000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '010', '002', 'ABSORVENTES', '96190000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '010', '003', 'TOA E LENC UMID', '96190000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '029', '001', 'ENLATA. E EM VD', '16041310', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '028', '001', 'COMUNS', '56012190', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '003', '005', 'REPARA DE PONTAS', '33059000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '038', '002', 'INSTANTANEOS', '19021900', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '046', '001', 'COMUNS', '48232099', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '011', '001', 'COMUNS', '18061000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('16', '010', '001', 'AGUA M', '22011000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('04', '001', '001', 'BOMBONS DE CHOC', '18069000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '011', '002', 'OUTROS', '21069030', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('04', '004', '001', 'EM GERAL', '20079910', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('50', '005', '001', 'LATEX', '21069010', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('50', '003', '001', 'GEL', '29051100', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('50', '003', '002', 'LIQUEDO', '22072010', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '006', '001', 'HIDRATANTES', '33072090', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('55', '003', '001', 'COMUNS', '34022000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('55', '022', '001', 'SALVA UNHAS', '68053090', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('55', '025', '001', 'PEDRAS', '38089999', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('02', '001', '001', 'AGUA DE COLONIA', '33030020', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '003', '006', 'DESCOLORANTE', '33059000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('09', '008', '001', 'COPOS DESCARTAVEIS', '39241000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('09', '004', '001', 'FILME DE PVC TRANS', '39201010', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '003', '002', 'VACUO', '09012100', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('13', '003', '001', 'CADERNO', '48202000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '058', '001', 'CALDOS', '21039021', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '058', '002', 'EM SACHE', '21039021', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('06', '002', '001', 'LANTERNAS', '85131010', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('11', '007', '001', 'EXTENSAO', '85444900', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '012', '004', 'LIXA P/ PES E MAOS', '82142000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '069', '001', 'SALGADOS', '19041000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '052', '001', 'BRANCO', '10063011', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '052', '002', 'PARBOLIZADO', '10063011', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('30', '002', '001', 'CACHACA', '22072020', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('30', '006', '001', 'CONHAQUE', '22089090', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('55', '004', '002', 'PO', '34012090', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '003', '007', 'ATIVADOR', '33059000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '003', '008', 'MASC CAP', '33059000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '003', '001', 'COMUNS', '09062000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('15', '002', '001', 'STEAK DE FRANGO', '16023230', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '022', '001', 'EM GERAL', '21069010', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '024', '002', 'COBERT', '19012000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('16', '011', '001', 'MARGARINA', '15171000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '065', '001', 'EM GERAL', '33019010', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('55', '005', '001', 'VASSOURAS', '96031000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('06', '003', '001', 'ULTRALED', '85437099', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('06', '003', '002', 'LED', '85437099', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '066', '001', 'EM GERAL', '11010010', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('16', '009', '001', 'COMUM', '20098990', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('55', '005', '002', 'RODOS', '96039000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('30', '001', '001', 'EM GERAL', '22082000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('55', '011', '001', 'AGUA SANI', '28289011', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('02', '002', '002', 'DESODORANTE', '33072010', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('06', '004', '001', 'HALOGENA', '85392190', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '014', '001', 'COMUNS', '96032100', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '003', '015', 'FIXADORES CAP', '33053000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('06', '001', '001', 'LUZ BRANCA', '85393100', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('06', '005', '001', 'ABAJUR', '94052000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('04', '001', '002', 'PAST. EM GEL', '17049020', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('09', '006', '001', 'DE PAPEL', '48183000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '055', '001', 'EM GERAL', '25010020', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('16', '001', '001', 'COMUM', '04031000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '029', '002', 'EM SACHE', '16041310', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('50', '006', '001', 'EM GERAL', '30067000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('16', '012', '001', 'LEITE FERMENTADO LIQ', '04039000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('55', '006', '001', 'POLIDOR', '34059000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '015', '001', 'EM GERAL', '19054000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('14', '003', '001', 'PAPEL P/ CIGARRO', '48131000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '017', '001', 'EM GERAL', '08013200', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('55', '019', '001', 'LIQUEDO', '34022000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('16', '005', '001', 'REFRIGERANTE 2L', '22021000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('16', '005', '002', 'REFRIGERANTES 500ML', '22021000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('16', '004', '001', 'DE FRUTAS', '22029000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('16', '004', '002', 'OUTROS', '22029000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('55', '022', '003', 'LA DE ACO', '73231000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '003', '003', 'SOLUVEL', '21011110', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '053', '001', 'EM GERAL', '17019900', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('11', '005', '001', 'COLAS', '19010110', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('16', '005', '003', 'CACULINHAS/LATA', '22021000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('16', '007', '001', 'COMUM', '22030000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('16', '005', '004', '1L', '22021000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '029', '001', 'EM GERAL', '33043000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '052', '003', 'INTEGRAL', '10062010', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '038', '003', 'INTEGRAIS', '19021900', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('12', '001', '001', 'EM GERAL', '39172900', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '010', '002', 'DE COCO', '20098990', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '010', '003', 'CONDENSADO', '04029900', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '010', '004', 'LIGHT', '04022120', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '010', '005', 'DESNATADO', '04022110', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '010', '006', 'SEM LACTOSE', '04012010', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '012', '005', 'PINCA P/ SOBRANCE', '82032090', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('04', '002', '001', 'BRANCO', '18063110', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('04', '002', '002', 'COMUM', '18063110', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('55', '004', '004', 'LIQUEDO', '34013000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '003', '004', 'EM GRAO', '09011110', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '003', '016', 'CR DE HID', '33049910', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '074', '001', 'COMUM', '10059010', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('50', '001', '001', 'COMUNS', '38089199', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '050', '001', 'EM GERAL', '21032090', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('12', '003', '001', 'EM GERAL', '39249000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('04', '001', '003', 'BALAS', '17049020', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('04', '001', '007', 'PIRULITO', '17049090', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('11', '006', '001', 'PALITO', '85061010', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('11', '009', '001', 'MINI', '96131000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('11', '009', '002', 'COMUM', '96131000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('04', '001', '004', 'CHICLETES', '17041000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('11', '006', '002', 'GRANDE', '85061010', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('11', '010', '001', 'EM GERAL', '82122010', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '074', '002', 'P/ PIPOCA', '11042300', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('55', '004', '005', 'PASTA', '34012090', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '004', '003', 'INTIMO', '34013000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '004', '004', 'FACIAL', '34013000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('12', '002', '001', 'EM GERAL', '40149090', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '074', '003', 'P/ CANJICA', '11042300', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('55', '026', '001', 'APA. AUTOMATICO', '33074900', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('55', '027', '001', 'CORDAS', '56079090', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '033', '001', 'EM GERAL', '20079910', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '023', '001', 'EM GERAL', '20081100', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '025', '001', 'FAR DE AVEIA', '11029000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '004', '001', 'COMUNS', '21069090', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('04', '002', '003', 'LEITE', '19019020', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('04', '002', '004', 'BATIDA', '22060090', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '073', '001', 'COMUNS', '11062000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '035', '001', 'EM GERAL', '21069029', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '073', '002', 'TEMPERADAS', '11062000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '016', '001', 'COMUNS', '18063110', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('55', '014', '001', 'ACIDO MURIATICO', '38259000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('55', '028', '001', 'LIQUEDO', '22072019', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('16', '002', '001', 'ACHOCOLATADOS', '22029000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '003', '009', 'AGUA OXI', '28470000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('55', '001', '001', 'COMUNS', '33074900', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('55', '007', '001', 'LIQUEDA', '34052000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('55', '007', '002', 'PASTA', '34059000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '008', '002', 'COMUNS', '30059090', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('55', '012', '001', 'COMUNS', '28289011', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '003', '017', 'CR DE TRAT', '33059000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('09', '025', '001', 'FORRO P/ FOGAO', '85166011', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('55', '029', '001', 'DESODORIZANTE', '33074900', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '044', '001', 'CUSCUZ', '19024000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('55', '019', '002', 'PASTA', '34012090', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '044', '002', 'FLOCAO', '11022000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('55', '026', '002', 'COMUNS', '33074900', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('55', '010', '001', 'COMUNS', '84133030', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('55', '013', '001', 'COMUNS', '27101919', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('55', '014', '002', 'SODA CAUSTICA', '28151200', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('55', '032', '001', 'COMUNS', '28322000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('55', '033', '001', 'COMUNS', '34029039', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('03', '001', '001', 'RACOES', '23091000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '003', '010', 'ALISANTE', '33052000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('55', '011', '002', 'ALVEJANTE', '28289019', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '033', '001', 'EM GERAL', '28142000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '001', '001', 'ANTISSEPTICO BUCAL', '33069000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '023', '001', 'COMUNS', '33041000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '006', '002', 'OUTROS CR', '33049910', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '009', '002', 'CR DE BARB', '33071000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '003', '011', 'TINTA', '33059000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '003', '012', 'DEFINIDOR', '33059000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '058', '003', 'LIQ E PASTAS', '21039029', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '022', '001', 'EM GERAL', '33043000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '003', '013', 'OLEOS', '33052000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '003', '014', 'FINALIZADOR', '33059000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '027', '001', 'EM GERAL', '33062000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '006', '003', 'LOCOES HID', '33049100', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '006', '004', 'OLEOS HID', '33072090', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '012', '006', 'SABONETEIRAS', '39229000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('02', '001', '002', 'PERFUME', '33030010', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('55', '023', '001', 'MADEIRA', '39249000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '012', '008', 'PALITOS DENT', '83040000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '012', '009', 'ESP DE BANHO', '96162000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '018', '001', 'COMUNS', '11081200', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '034', '001', 'COMUNS', '33049100', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '058', '004', 'EM POTE', '09041200', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '026', '003', 'P/ OS PES', '33072010', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '016', '001', 'COMUNS', '39249000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('11', '004', '001', 'VELA', '34060000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '027', '001', 'COMUNS', '08011100', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '026', '004', 'SPRAY', '33072010', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '079', '001', 'GOMA', '17041000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '021', '001', 'EM GERAL', '12040090', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('16', '013', '001', 'POLPA', '20089900', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('16', '014', '001', 'NATA', '04014029', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('15', '001', '001', 'EM GERAL', '16025000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('04', '003', '001', 'BOLINHOS', '19052090', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('15', '004', '001', 'EM GERAL', '03049900', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('55', '017', '001', 'COMUM', '39232190', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '026', '001', 'EM GERAL', '16024900', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '032', '001', 'EM GERAL', '22021000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '028', '001', 'EM GERAL', '07135010', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('50', '007', '001', 'EM GERAL', '33049900', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '019', '001', 'EM GERAL', '11041200', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('11', '001', '001', 'COMUM', '44211000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('09', '008', '002', 'COPOS PLASTICOS', '39241000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('55', '028', '002', 'GEL', '29051100', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('09', '002', '001', 'DE ALUMINIO', '76101000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('09', '009', '001', '1,8L', '39233000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('55', '027', '002', 'DE ACO', '73239900', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('09', '008', '003', 'CANECOS DE PORCELANA', '69141000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('55', '025', '002', 'PASTILHAS', '38089999', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('09', '016', '001', 'DE VIDRO', '70133700', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('09', '001', '001', 'EM GERAL', '39241000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('09', '026', '001', 'DE VIDRO', '70109012', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('09', '027', '001', 'DE VIDRO', '70134290', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('55', '023', '002', 'PLASTICO', '39249000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('55', '024', '001', 'COMUNS', '63071000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('55', '021', '002', '1L', '38099190', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('55', '021', '003', '2L', '38099190', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('55', '021', '004', '5L', '38099190', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('09', '006', '002', 'DE TECIDO', '63080000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '018', '002', 'OUTROS', '19011030', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('55', '008', '004', 'LAVA PISOS 2L', '38089429', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('55', '008', '005', 'LAVA PISOS 500ML', '38089429', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('55', '008', '003', 'LAVA PISOS 750ML', '38089429', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('55', '003', '002', 'LIMPA VIDROS', '34022000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '044', '003', 'CANJICA', '32041913', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('55', '034', '001', 'P/LAVAR', '96039000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('55', '034', '002', 'SANITARIAS', '96039000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('55', '035', '001', 'AEROSOL', '38089119', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '002', '001', 'COMUNS', '21069029', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('55', '035', '002', 'APA. ELETRICOS', '38089119', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('55', '036', '001', 'EM GERAL', '34053000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '009', '003', 'LAINAS DE BARB', '82122010', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '005', '001', 'COMUNS', '19023000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('55', '002', '001', 'EM GERAL', '39172900', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('50', '004', '001', 'COMUNS', '17023020', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '006', '001', 'COMUNS', '21023000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '035', '001', 'COMUNS', '29141100', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '007', '001', 'EM GERAL', '17029000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '044', '004', 'FUBA', '11022000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '010', '007', 'CR DE LEITE', '04022130', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('11', '011', '001', 'EM GERAL', '95044000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('09', '011', '001', 'EM GERAL', '82159910', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('25', '002', '001', 'EM GERAL', '19059010', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('14', '001', '001', 'EM GERAL', '24022000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('11', '003', '001', 'EM GERAL', '36050000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '075', '001', 'EM GERAL', '07133399', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('14', '002', '001', 'EM GERAL', '24022000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('15', '005', '001', 'EM GERAL', '16010000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('08', '001', '001', 'EM GERAL', '39241000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('16', '008', '001', 'EM GERAL', '04061090', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('13', '004', '001', 'EM GERAL', '40011000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('13', '005', '001', 'EM GERAL', '96082000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('13', '002', '001', 'EM GERAL', '96091000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('09', '003', '001', 'EM GERAL', '76071990', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '020', '001', 'COMUNS', '19059090', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '074', '004', 'P/ MUNG', '11042300', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('18', '001', '001', 'EM GERAL', '12119090', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('18', '002', '001', 'EM GERAL', '07096000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('18', '003', '001', 'EM GERAL', '21039091', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('25', '003', '001', 'EM GERAL', '19012000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('15', '006', '001', 'EM GERAL', '04061010', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '036', '001', 'EM GERAL', '33079000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('15', '007', '001', 'EM GERAL', '02071400', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('13', '006', '001', 'EM GERAL', '38249029', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('13', '001', '001', 'EM GERAL', '96082000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('50', '008', '001', 'EM GERAL', '33049990', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '078', '001', 'EM GERAL', '04071100', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '080', '001', 'EM GERAL', '21041011', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('16', '015', '001', 'EM GERAL', '21050010', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('15', '003', '001', 'EM GERAL', '02023000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '037', '001', 'EM GERAL', '34011900', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('08', '002', '001', 'EM GERAL', '95059000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('08', '003', '001', 'EM GERAL', '48239099', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('08', '004', '001', 'EM GERAL', '34060000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('16', '016', '001', 'EM GERAL', '19022000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('13', '007', '001', 'BRANCA', '35061090', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('13', '008', '001', 'EM GERAL', '82130000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('13', '009', '001', 'EM GERAL', '39261000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '038', '001', 'EM GERAL', '33042010', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('09', '008', '004', 'DE VIDRO', '70071900', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('50', '009', '001', 'EM GERAL', '30051090', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('09', '018', '001', 'DE METAL', '82055100', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('13', '010', '001', 'EM GERAL', '39261000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('12', '005', '001', 'EM GERAL', '95030080', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('11', '008', '001', 'EM GERAL', '62029900', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('09', '024', '001', 'EM GERAL', '40169300', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '070', '001', 'EM GERAL', '20052000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('15', '008', '001', 'EM GERAL', '16025000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('09', '007', '001', 'GARRAFAS TERMICAS', '96170010', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('09', '007', '002', 'CANTIL TERMICOS', '39233000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '072', '001', 'EM GERAL', '04062000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('13', '011', '001', 'EM GERAL', '42021210', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('13', '012', '001', 'EM GERAL', '39261000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('13', '007', '002', 'DE ISOPOR', '35061090', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('13', '007', '003', 'COM GLITTER', '35061090', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('13', '009', '002', 'METAL', '82141000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('09', '016', '002', 'PORCELANA', '69141000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('09', '014', '001', 'DE ACO', '96040000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('09', '017', '001', 'DE VIDRO', '70134900', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('09', '021', '001', 'DE PLASTICO', '39239000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('04', '002', '005', 'DE FRUTAS', '20071000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('11', '017', '001', 'EM GERAL', '85044060', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('13', '013', '001', 'EM GERAL', '84729040', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('15', '009', '001', 'EM GERAL', '16024900', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('01', '071', '001', 'EM GERAL', '19030000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '012', '010', 'ITENS PLASTICOS EM GERAL', '39159000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('09', '014', '002', 'PLASTICA', '39172900', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('16', '006', '001', 'EM GERAL', '35071000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('12', '006', '001', 'EM GERAL', '', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('12', '007', '001', 'DIVERSOS', '', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '039', '001', 'DIVERSOS', '', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('07', '001', '002', 'HAV. COLOR', '64022000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('15', '010', '001', 'EM GERAL', '16010000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('17', '001', '001', 'EM GERAL', '85044090', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('09', '028', '001', 'EM GERAL', '76151000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('04', '006', '001', 'EM GERAL', '', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('18', '004', '001', 'BATATA INGLESA', '07101000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('09', '008', '005', 'ALUMINIO', '76151000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('15', '011', '001', 'EM GERAL', '16023100', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('55', '020', '001', 'EM GERAL', '34052000', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('35', '012', '011', 'MASCARAS', '63079010', 'N', 'S', 5, 'N');
INSERT INTO SUBGRUPO (SECCOD, GRPCOD, SGRCOD, SGRDES, SGRNCM, SGRPARTREGESP, SGRCONFPESOSC, SGRPERCDIVPESOSC, SGRSINCLD)
              VALUES ('00', '000', '000', 'SUBGRUPO PADRAO', NULL, NULL, 'S', 5, 'N');


COMMIT WORK;

